/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './users.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/platform-browser';
import * as import4 from '@angular/forms';
import * as import5 from '@angular/router';
import * as import6 from '@angular/http';
import * as import7 from './users-routing.module';
import * as import8 from './user.service';
import * as import9 from './login/login.component.ngfactory';
import * as import10 from './register/register.component.ngfactory';
import * as import11 from './logout/logout.component.ngfactory';
import * as import12 from './login/login.component';
import * as import13 from './register/register.component';
import * as import14 from './logout/logout.component';
class UsersModuleInjector extends import0.ɵNgModuleInjector<import1.UsersModule> {
  _CommonModule_0:import2.CommonModule;
  _ErrorHandler_1:any;
  _APP_INITIALIZER_2:any[];
  _ApplicationInitStatus_3:import0.ApplicationInitStatus;
  _ɵf_4:import0.ɵf;
  _ApplicationRef_5:any;
  _ApplicationModule_6:import0.ApplicationModule;
  _BrowserModule_7:import3.BrowserModule;
  _ɵba_8:import4.ɵba;
  _FormsModule_9:import4.FormsModule;
  _RouterModule_10:import5.RouterModule;
  _HttpModule_11:import6.HttpModule;
  _UsersRoutingModule_12:import7.UsersRoutingModule;
  _ReactiveFormsModule_13:import4.ReactiveFormsModule;
  _UsersModule_14:import1.UsersModule;
  __LOCALE_ID_15:any;
  __NgLocalization_16:import2.NgLocaleLocalization;
  __Compiler_17:import0.Compiler;
  __APP_ID_18:any;
  __IterableDiffers_19:any;
  __KeyValueDiffers_20:any;
  __DomSanitizer_21:import3.ɵe;
  __Sanitizer_22:any;
  __HAMMER_GESTURE_CONFIG_23:import3.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_24:any[];
  __EventManager_25:import3.EventManager;
  __ɵDomSharedStylesHost_26:import3.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_27:import3.ɵDomRendererFactory2;
  __RendererFactory2_28:any;
  __ɵSharedStylesHost_29:any;
  __Testability_30:import0.Testability;
  __Meta_31:import3.Meta;
  __Title_32:import3.Title;
  __ɵi_33:import4.ɵi;
  __BrowserXhr_34:import6.BrowserXhr;
  __ResponseOptions_35:import6.BaseResponseOptions;
  __XSRFStrategy_36:any;
  __XHRBackend_37:import6.XHRBackend;
  __RequestOptions_38:import6.BaseRequestOptions;
  __Http_39:any;
  _ROUTES_40:any[];
  __FormBuilder_41:import4.FormBuilder;
  __UserService_42:import8.UserService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import9.LoginComponentNgFactory,
      import10.RegisterComponentNgFactory,
      import11.LogoutComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _LOCALE_ID_15():any {
    if ((this.__LOCALE_ID_15 == null)) { (this.__LOCALE_ID_15 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_15;
  }
  get _NgLocalization_16():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_16 == null)) { (this.__NgLocalization_16 = new import2.NgLocaleLocalization(this._LOCALE_ID_15)); }
    return this.__NgLocalization_16;
  }
  get _Compiler_17():import0.Compiler {
    if ((this.__Compiler_17 == null)) { (this.__Compiler_17 = new import0.Compiler()); }
    return this.__Compiler_17;
  }
  get _APP_ID_18():any {
    if ((this.__APP_ID_18 == null)) { (this.__APP_ID_18 = import0.ɵg()); }
    return this.__APP_ID_18;
  }
  get _IterableDiffers_19():any {
    if ((this.__IterableDiffers_19 == null)) { (this.__IterableDiffers_19 = import0.ɵl()); }
    return this.__IterableDiffers_19;
  }
  get _KeyValueDiffers_20():any {
    if ((this.__KeyValueDiffers_20 == null)) { (this.__KeyValueDiffers_20 = import0.ɵm()); }
    return this.__KeyValueDiffers_20;
  }
  get _DomSanitizer_21():import3.ɵe {
    if ((this.__DomSanitizer_21 == null)) { (this.__DomSanitizer_21 = new import3.ɵe(this.parent.get(import3.DOCUMENT))); }
    return this.__DomSanitizer_21;
  }
  get _Sanitizer_22():any {
    if ((this.__Sanitizer_22 == null)) { (this.__Sanitizer_22 = this._DomSanitizer_21); }
    return this.__Sanitizer_22;
  }
  get _HAMMER_GESTURE_CONFIG_23():import3.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_23 == null)) { (this.__HAMMER_GESTURE_CONFIG_23 = new import3.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_23;
  }
  get _EVENT_MANAGER_PLUGINS_24():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_24 == null)) { (this.__EVENT_MANAGER_PLUGINS_24 = [
      new import3.ɵDomEventsPlugin(this.parent.get(import3.DOCUMENT)),
      new import3.ɵKeyEventsPlugin(this.parent.get(import3.DOCUMENT)),
      new import3.ɵHammerGesturesPlugin(this.parent.get(import3.DOCUMENT),this._HAMMER_GESTURE_CONFIG_23)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_24;
  }
  get _EventManager_25():import3.EventManager {
    if ((this.__EventManager_25 == null)) { (this.__EventManager_25 = new import3.EventManager(this._EVENT_MANAGER_PLUGINS_24,this.parent.get(import0.NgZone))); }
    return this.__EventManager_25;
  }
  get _ɵDomSharedStylesHost_26():import3.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_26 == null)) { (this.__ɵDomSharedStylesHost_26 = new import3.ɵDomSharedStylesHost(this.parent.get(import3.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_26;
  }
  get _ɵDomRendererFactory2_27():import3.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_27 == null)) { (this.__ɵDomRendererFactory2_27 = new import3.ɵDomRendererFactory2(this._EventManager_25,this._ɵDomSharedStylesHost_26)); }
    return this.__ɵDomRendererFactory2_27;
  }
  get _RendererFactory2_28():any {
    if ((this.__RendererFactory2_28 == null)) { (this.__RendererFactory2_28 = this._ɵDomRendererFactory2_27); }
    return this.__RendererFactory2_28;
  }
  get _ɵSharedStylesHost_29():any {
    if ((this.__ɵSharedStylesHost_29 == null)) { (this.__ɵSharedStylesHost_29 = this._ɵDomSharedStylesHost_26); }
    return this.__ɵSharedStylesHost_29;
  }
  get _Testability_30():import0.Testability {
    if ((this.__Testability_30 == null)) { (this.__Testability_30 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_30;
  }
  get _Meta_31():import3.Meta {
    if ((this.__Meta_31 == null)) { (this.__Meta_31 = new import3.Meta(this.parent.get(import3.DOCUMENT))); }
    return this.__Meta_31;
  }
  get _Title_32():import3.Title {
    if ((this.__Title_32 == null)) { (this.__Title_32 = new import3.Title(this.parent.get(import3.DOCUMENT))); }
    return this.__Title_32;
  }
  get _ɵi_33():import4.ɵi {
    if ((this.__ɵi_33 == null)) { (this.__ɵi_33 = new import4.ɵi()); }
    return this.__ɵi_33;
  }
  get _BrowserXhr_34():import6.BrowserXhr {
    if ((this.__BrowserXhr_34 == null)) { (this.__BrowserXhr_34 = new import6.BrowserXhr()); }
    return this.__BrowserXhr_34;
  }
  get _ResponseOptions_35():import6.BaseResponseOptions {
    if ((this.__ResponseOptions_35 == null)) { (this.__ResponseOptions_35 = new import6.BaseResponseOptions()); }
    return this.__ResponseOptions_35;
  }
  get _XSRFStrategy_36():any {
    if ((this.__XSRFStrategy_36 == null)) { (this.__XSRFStrategy_36 = import6.ɵb()); }
    return this.__XSRFStrategy_36;
  }
  get _XHRBackend_37():import6.XHRBackend {
    if ((this.__XHRBackend_37 == null)) { (this.__XHRBackend_37 = new import6.XHRBackend(this._BrowserXhr_34,this._ResponseOptions_35,this._XSRFStrategy_36)); }
    return this.__XHRBackend_37;
  }
  get _RequestOptions_38():import6.BaseRequestOptions {
    if ((this.__RequestOptions_38 == null)) { (this.__RequestOptions_38 = new import6.BaseRequestOptions()); }
    return this.__RequestOptions_38;
  }
  get _Http_39():any {
    if ((this.__Http_39 == null)) { (this.__Http_39 = import6.ɵc(this._XHRBackend_37,this._RequestOptions_38)); }
    return this.__Http_39;
  }
  get _FormBuilder_41():import4.FormBuilder {
    if ((this.__FormBuilder_41 == null)) { (this.__FormBuilder_41 = new import4.FormBuilder()); }
    return this.__FormBuilder_41;
  }
  get _UserService_42():import8.UserService {
    if ((this.__UserService_42 == null)) { (this.__UserService_42 = new import8.UserService(this._Http_39,this.parent.get(import5.Router))); }
    return this.__UserService_42;
  }
  createInternal():import1.UsersModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ErrorHandler_1 = import3.ɵa();
    this._APP_INITIALIZER_2 = [
      import0.ɵo,
      import3.ɵc(this.parent.get(import3.NgProbeToken,(null as any)),this.parent.get(import0.NgProbeToken,(null as any)))
    ]
    ;
    this._ApplicationInitStatus_3 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_2);
    this._ɵf_4 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_1,this.componentFactoryResolver,this._ApplicationInitStatus_3);
    this._ApplicationRef_5 = this._ɵf_4;
    this._ApplicationModule_6 = new import0.ApplicationModule(this._ApplicationRef_5);
    this._BrowserModule_7 = new import3.BrowserModule(this.parent.get(import3.BrowserModule,(null as any)));
    this._ɵba_8 = new import4.ɵba();
    this._FormsModule_9 = new import4.FormsModule();
    this._RouterModule_10 = new import5.RouterModule(this.parent.get(import5.ɵa,(null as any)),this.parent.get(import5.Router,(null as any)));
    this._HttpModule_11 = new import6.HttpModule();
    this._UsersRoutingModule_12 = new import7.UsersRoutingModule();
    this._ReactiveFormsModule_13 = new import4.ReactiveFormsModule();
    this._UsersModule_14 = new import1.UsersModule();
      this._ROUTES_40 = [[
        {
          path: 'login',
          component: import12.LoginComponent,
          name: 'Login',
          useAsDefault: true
        }
        ,
        {
          path: 'register',
          component: import13.RegisterComponent,
          name: 'Register'
        }
        ,
        {
          path: 'logout',
          component: import14.LogoutComponent,
          name: 'Logout'
        }

      ]
    ];
    return this._UsersModule_14;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_1; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_2; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_3; }
    if ((token === import0.ɵf)) { return this._ɵf_4; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_5; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_6; }
    if ((token === import3.BrowserModule)) { return this._BrowserModule_7; }
    if ((token === import4.ɵba)) { return this._ɵba_8; }
    if ((token === import4.FormsModule)) { return this._FormsModule_9; }
    if ((token === import5.RouterModule)) { return this._RouterModule_10; }
    if ((token === import6.HttpModule)) { return this._HttpModule_11; }
    if ((token === import7.UsersRoutingModule)) { return this._UsersRoutingModule_12; }
    if ((token === import4.ReactiveFormsModule)) { return this._ReactiveFormsModule_13; }
    if ((token === import1.UsersModule)) { return this._UsersModule_14; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_15; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_16; }
    if ((token === import0.Compiler)) { return this._Compiler_17; }
    if ((token === import0.APP_ID)) { return this._APP_ID_18; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_19; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_20; }
    if ((token === import3.DomSanitizer)) { return this._DomSanitizer_21; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_22; }
    if ((token === import3.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_23; }
    if ((token === import3.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_24; }
    if ((token === import3.EventManager)) { return this._EventManager_25; }
    if ((token === import3.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_26; }
    if ((token === import3.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_27; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_28; }
    if ((token === import3.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_29; }
    if ((token === import0.Testability)) { return this._Testability_30; }
    if ((token === import3.Meta)) { return this._Meta_31; }
    if ((token === import3.Title)) { return this._Title_32; }
    if ((token === import4.ɵi)) { return this._ɵi_33; }
    if ((token === import6.BrowserXhr)) { return this._BrowserXhr_34; }
    if ((token === import6.ResponseOptions)) { return this._ResponseOptions_35; }
    if ((token === import6.XSRFStrategy)) { return this._XSRFStrategy_36; }
    if ((token === import6.XHRBackend)) { return this._XHRBackend_37; }
    if ((token === import6.RequestOptions)) { return this._RequestOptions_38; }
    if ((token === import6.Http)) { return this._Http_39; }
    if ((token === import5.ROUTES)) { return this._ROUTES_40; }
    if ((token === import4.FormBuilder)) { return this._FormBuilder_41; }
    if ((token === import8.UserService)) { return this._UserService_42; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_4.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_26 && this._ɵDomSharedStylesHost_26.ngOnDestroy());
  }
}
export const UsersModuleNgFactory:import0.NgModuleFactory<import1.UsersModule> = new import0.NgModuleFactory<any>(UsersModuleInjector,import1.UsersModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1ZvbHVtZXMvRy1EUklWRS9teURpcmVjdG9yeS9zZWVkX25vZGVqc0FuZ3VsYXJNeXNxbDAyL2Fzc2V0cy9hcHAvdXNlcnMvdXNlcnMubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1ZvbHVtZXMvRy1EUklWRS9teURpcmVjdG9yeS9zZWVkX25vZGVqc0FuZ3VsYXJNeXNxbDAyL2Fzc2V0cy9hcHAvdXNlcnMvdXNlcnMubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
