/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '@angular/flex-layout/flexbox/api/class';
import * as import2 from '@angular/flex-layout/media-query/media-monitor';
import * as import3 from './tab';
const styles_Tab:any[] = ['.pane[_ngcontent-%COMP%]{\n      padding: 1em;\n    }'];
export const RenderType_Tab:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_Tab,
  data: {}
}
);
export function View_Tab_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'pane'
      ]
      ],[[
        8,
        'hidden',
        0
      ]
    ],(null as any),(null as any),(null as any),(null as any))),
    import0.ɵdid(933888,(null as any),0,import1.ClassDirective,[
      import2.MediaMonitor,
      import0.IterableDiffers,
      import0.KeyValueDiffers,
      import0.ElementRef,
      import0.Renderer,
      import0.Renderer2
    ]
      ,{classBase: [
        0,
        'classBase'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n      '])),
    import0.ɵncd((null as any),0),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(ck,v) => {
    const currVal_1:any = 'pane';
    ck(v,2,0,currVal_1);
  },(ck,v) => {
    var co:import3.Tab = v.component;
    const currVal_0:boolean = !co.active;
    ck(v,1,0,currVal_0);
  });
}
function View_Tab_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'tab',([] as any[]),(null as any),(null as any),(null as any),View_Tab_0,RenderType_Tab)),
    import0.ɵdid(49152,(null as any),0,import3.Tab,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const TabNgFactory:import0.ComponentFactory<import3.Tab> = import0.ɵccf('tab',import3.Tab,View_Tab_Host_0,{
  title: 'tabTitle',
  active: 'active'
}
,{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1ZvbHVtZXMvRy1EUklWRS9teURpcmVjdG9yeS9zZWVkX25vZGVqc0FuZ3VsYXJNeXNxbDAyL2Fzc2V0cy9hcHAvc2hhcmVkL3RhYi5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Wb2x1bWVzL0ctRFJJVkUvbXlEaXJlY3Rvcnkvc2VlZF9ub2RlanNBbmd1bGFyTXlzcWwwMi9hc3NldHMvYXBwL3NoYXJlZC90YWIudHMiLCJuZzovLy9Wb2x1bWVzL0ctRFJJVkUvbXlEaXJlY3Rvcnkvc2VlZF9ub2RlanNBbmd1bGFyTXlzcWwwMi9hc3NldHMvYXBwL3NoYXJlZC90YWIudHMuVGFiLmh0bWwiLCJuZzovLy9Wb2x1bWVzL0ctRFJJVkUvbXlEaXJlY3Rvcnkvc2VlZF9ub2RlanNBbmd1bGFyTXlzcWwwMi9hc3NldHMvYXBwL3NoYXJlZC90YWIudHMuVGFiX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgPGRpdiBbaGlkZGVuXT1cIiFhY3RpdmVcIiBjbGFzcz1cInBhbmVcIj5cbiAgICAgIDxuZy1jb250ZW50PjwvbmctY29udGVudD5cbiAgICA8L2Rpdj5cbiAgIiwiPHRhYj48L3RhYj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtNQUNJO1FBQUE7UUFBQTtNQUFBO01BQUE7UUFBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO2dCQUFBOzs7Ozs7O0lBQUE7T0FBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXFDO2dCQUNuQztJQUF5QjtJQUNyQjs7O0lBRmtCO0lBQXhCLFNBQXdCLFNBQXhCOzs7SUFBSztJQUFMLFNBQUssU0FBTDs7Ozs7SUNESjtnQkFBQTs7Ozs7Ozs7In0=
