/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '@angular/flex-layout/flexbox/api/class';
import * as import2 from '@angular/flex-layout/media-query/media-monitor';
import * as import3 from '@angular/common';
import * as import4 from './tabs';
const styles_Tabs:any[] = ([] as any[]);
export const RenderType_Tabs:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_Tabs,
  data: {}
}
);
function View_Tabs_1(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'li',([] as any[]),[[
        2,
        'active',
        (null as any)
      ]
      ],[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:any = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.selectTab(v.context.$implicit)) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'a',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n      ']))
  ]
  ,(null as any),(ck,v) => {
    const currVal_0:any = v.context.$implicit.active;
    ck(v,0,0,currVal_0);
    const currVal_1:any = v.context.$implicit.title;
    ck(v,3,0,currVal_1);
  });
}
export function View_Tabs_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),5,'ul',[[
        'class',
        'nav nav-tabs'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    import0.ɵdid(933888,(null as any),0,import1.ClassDirective,[
      import2.MediaMonitor,
      import0.IterableDiffers,
      import0.KeyValueDiffers,
      import0.ElementRef,
      import0.Renderer,
      import0.Renderer2
    ]
      ,{classBase: [
        0,
        'classBase'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n      '])),
    (l()(),import0.ɵand(16777216,(null as any),(null as any),1,(null as any),View_Tabs_1)),
    import0.ɵdid(802816,(null as any),0,import3.NgForOf,[
      import0.ViewContainerRef,
      import0.TemplateRef,
      import0.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵted((null as any),['\n    '])),
    import0.ɵncd((null as any),0),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(ck,v) => {
    var co:import4.Tabs = v.component;
    const currVal_0:any = 'nav nav-tabs';
    ck(v,2,0,currVal_0);
    const currVal_1:any = co.tabs;
    ck(v,5,0,currVal_1);
  },(null as any));
}
function View_Tabs_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),2,'tabs',([] as any[]),(null as any),(null as any),(null as any),View_Tabs_0,RenderType_Tabs)),
    import0.ɵdid(1097728,(null as any),1,import4.Tabs,([] as any[]),(null as any),(null as any)),
    import0.ɵqud(603979776,1,{tabs: 1})
  ]
  ,(null as any),(null as any));
}
export const TabsNgFactory:import0.ComponentFactory<import4.Tabs> = import0.ɵccf('tabs',import4.Tabs,View_Tabs_Host_0,{},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1ZvbHVtZXMvRy1EUklWRS9teURpcmVjdG9yeS9zZWVkX25vZGVqc0FuZ3VsYXJNeXNxbDAyL2Fzc2V0cy9hcHAvc2hhcmVkL3RhYnMubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVm9sdW1lcy9HLURSSVZFL215RGlyZWN0b3J5L3NlZWRfbm9kZWpzQW5ndWxhck15c3FsMDIvYXNzZXRzL2FwcC9zaGFyZWQvdGFicy50cyIsIm5nOi8vL1ZvbHVtZXMvRy1EUklWRS9teURpcmVjdG9yeS9zZWVkX25vZGVqc0FuZ3VsYXJNeXNxbDAyL2Fzc2V0cy9hcHAvc2hhcmVkL3RhYnMudHMuVGFicy5odG1sIiwibmc6Ly8vVm9sdW1lcy9HLURSSVZFL215RGlyZWN0b3J5L3NlZWRfbm9kZWpzQW5ndWxhck15c3FsMDIvYXNzZXRzL2FwcC9zaGFyZWQvdGFicy50cy5UYWJzX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgPHVsIGNsYXNzPVwibmF2IG5hdi10YWJzXCI+XG4gICAgICA8bGkgKm5nRm9yPVwibGV0IHRhYiBvZiB0YWJzXCIgKGNsaWNrKT1cInNlbGVjdFRhYih0YWIpXCIgW2NsYXNzLmFjdGl2ZV09XCJ0YWIuYWN0aXZlXCI+XG4gICAgICAgIDxhPnt7dGFiLnRpdGxlfX08L2E+XG4gICAgICA8L2xpPlxuICAgIDwvdWw+XG4gICAgPG5nLWNvbnRlbnQ+PC9uZy1jb250ZW50PlxuICAiLCI8dGFicz48L3RhYnM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztNQ0VNO1FBQUE7UUFBQTtRQUFBO01BQUE7TUFBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO01BQUE7TUFBQTtNQUE2QjtRQUFBO1FBQUE7TUFBQTtNQUE3QjtJQUFBO0lBQWtGO0lBQ2hGO0lBQUc7TUFBQTtNQUFBO0lBQUE7SUFBQTtJQUFpQjs7O0lBRGdDO0lBQXRELFNBQXNELFNBQXREO0lBQ0s7SUFBQTs7Ozs7SUFIWDtNQUNJO1FBQUE7UUFBQTtNQUFBO0lBQUE7Z0JBQUE7Ozs7Ozs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBeUI7SUFDdkI7Z0JBQUE7Ozs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFFSztJQUNGO2dCQUNMO0lBQXlCOzs7O0lBTHJCO0lBQUosU0FBSSxTQUFKO0lBQ007SUFBSixTQUFJLFNBQUo7Ozs7O0lDRk47Z0JBQUE7Z0JBQUE7Ozs7In0=
