/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './logout.component';
const styles_LogoutComponent:any[] = ([] as any[]);
export const RenderType_LogoutComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_LogoutComponent,
  data: {}
}
);
export function View_LogoutComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n      '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'col-md-8 col-md-offset-2'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n          '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'button',[[
        'class',
        'btn btn-danger'
      ]
      ],(null as any),[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import1.LogoutComponent = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.logout()) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Logout'])),
    (l()(),import0.ɵted((null as any),['\n      '])),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(null as any),(null as any));
}
function View_LogoutComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-logout',([] as any[]),(null as any),(null as any),(null as any),View_LogoutComponent_0,RenderType_LogoutComponent)),
    import0.ɵdid(114688,(null as any),0,import1.LogoutComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const LogoutComponentNgFactory:import0.ComponentFactory<import1.LogoutComponent> = import0.ɵccf('app-logout',import1.LogoutComponent,View_LogoutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1ZvbHVtZXMvRy1EUklWRS9teURpcmVjdG9yeS9zZWVkX25vZGVqc0FuZ3VsYXJNeXNxbDAyL2Fzc2V0cy9hcHAvdXNlcnMvbG9nb3V0L2xvZ291dC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVm9sdW1lcy9HLURSSVZFL215RGlyZWN0b3J5L3NlZWRfbm9kZWpzQW5ndWxhck15c3FsMDIvYXNzZXRzL2FwcC91c2Vycy9sb2dvdXQvbG9nb3V0LmNvbXBvbmVudC50cyIsIm5nOi8vL1ZvbHVtZXMvRy1EUklWRS9teURpcmVjdG9yeS9zZWVkX25vZGVqc0FuZ3VsYXJNeXNxbDAyL2Fzc2V0cy9hcHAvdXNlcnMvbG9nb3V0L2xvZ291dC5jb21wb25lbnQudHMuTG9nb3V0Q29tcG9uZW50Lmh0bWwiLCJuZzovLy9Wb2x1bWVzL0ctRFJJVkUvbXlEaXJlY3Rvcnkvc2VlZF9ub2RlanNBbmd1bGFyTXlzcWwwMi9hc3NldHMvYXBwL3VzZXJzL2xvZ291dC9sb2dvdXQuY29tcG9uZW50LnRzLkxvZ291dENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgPGRpdiBjbGFzcz1cImNvbC1tZC04IGNvbC1tZC1vZmZzZXQtMlwiPlxuICAgICAgICAgIDxidXR0b24gY2xhc3M9XCJidG4gYnRuLWRhbmdlclwiIChjbGljayk9XCJsb2dvdXQoKVwiPkxvZ291dDwvYnV0dG9uPlxuICAgICAgPC9kaXY+XG4gICIsIjxhcHAtbG9nb3V0PjwvYXBwLWxvZ291dD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7TUFDTTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXNDO01BQ2xDO1FBQUE7UUFBQTtNQUFBO01BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtNQUFBO01BQUE7TUFBK0I7UUFBQTtRQUFBO01BQUE7TUFBL0I7SUFBQTtJQUFrRDtJQUFlO0lBQy9EOzs7Ozs7SUNIWjtnQkFBQTs7O0lBQUE7OzsifQ==
