/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './not-found.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from './not-found.component';
import * as import3 from '@angular/router';
const styles_NotFoundComponent:any[] = [import0.styles];
export const RenderType_NotFoundComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_NotFoundComponent,
  data: {}
}
);
export function View_NotFoundComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵted((null as any),['  '])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'h4',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['Not Found : 404'])),
    (l()(),import1.ɵted((null as any),['\n '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),1,'button',([] as any[]),(null as any),[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import2.NotFoundComponent = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.goToCompanies()) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),[' Go To Home '])),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(null as any),(null as any));
}
function View_NotFoundComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'app-not-found',([] as any[]),(null as any),(null as any),(null as any),View_NotFoundComponent_0,RenderType_NotFoundComponent)),
    import1.ɵdid(114688,(null as any),0,import2.NotFoundComponent,[import3.Router],(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const NotFoundComponentNgFactory:import1.ComponentFactory<import2.NotFoundComponent> = import1.ɵccf('app-not-found',import2.NotFoundComponent,View_NotFoundComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1ZvbHVtZXMvRy1EUklWRS9teURpcmVjdG9yeS9zZWVkX25vZGVqc0FuZ3VsYXJNeXNxbDAyL2Fzc2V0cy9hcHAvbm90LWZvdW5kL25vdC1mb3VuZC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVm9sdW1lcy9HLURSSVZFL215RGlyZWN0b3J5L3NlZWRfbm9kZWpzQW5ndWxhck15c3FsMDIvYXNzZXRzL2FwcC9ub3QtZm91bmQvbm90LWZvdW5kLmNvbXBvbmVudC50cyIsIm5nOi8vL1ZvbHVtZXMvRy1EUklWRS9teURpcmVjdG9yeS9zZWVkX25vZGVqc0FuZ3VsYXJNeXNxbDAyL2Fzc2V0cy9hcHAvbm90LWZvdW5kL25vdC1mb3VuZC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1ZvbHVtZXMvRy1EUklWRS9teURpcmVjdG9yeS9zZWVkX25vZGVqc0FuZ3VsYXJNeXNxbDAyL2Fzc2V0cy9hcHAvbm90LWZvdW5kL25vdC1mb3VuZC5jb21wb25lbnQudHMuTm90Rm91bmRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCIgIDxoND5Ob3QgRm91bmQgOiA0MDQ8L2g0PlxuIDxidXR0b24gKGNsaWNrKT1cIiBnb1RvQ29tcGFuaWVzKClcIj4gR28gVG8gSG9tZSA8L2J1dHRvbj5cbiIsIjxhcHAtbm90LWZvdW5kPjwvYXBwLW5vdC1mb3VuZD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFFO0lBQUk7SUFBb0I7TUFDekI7UUFBQTtRQUFBO01BQUE7SUFBQTtNQUFBO01BQUE7TUFBUTtRQUFBO1FBQUE7TUFBQTtNQUFSO0lBQUE7SUFBbUM7SUFBcUI7Ozs7OztJQ0R6RDtnQkFBQTs7O0lBQUE7OzsifQ==
