/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './address.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '@angular/common';
import * as import3 from './address.component';
import * as import4 from '../../company/company.service';
const styles_AddressComponent:any[] = [import0.styles];
export const RenderType_AddressComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_AddressComponent,
  data: {}
}
);
function View_AddressComponent_1(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),3,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),[
      '',
      ' '
    ]
    )),
    (l()(),import1.ɵeld(0,(null as any),(null as any),0,'br',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),[' ']))
  ]
  ,(null as any),(ck,v) => {
    var co:any = v.component;
    const currVal_0:any = co.street2;
    ck(v,1,0,currVal_0);
  });
}
export function View_AddressComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
      (l()(),import1.ɵeld(0,(null as any),(null as any),10,'div',[[
        'class',
        'container'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),[
      '\n    ',
      ''
    ]
    )),
    (l()(),import1.ɵeld(0,(null as any),(null as any),0,'br',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),[' \n    '])),
    (l()(),import1.ɵand(16777216,(null as any),(null as any),1,(null as any),View_AddressComponent_1)),
    import1.ɵdid(16384,(null as any),0,import2.NgIf,[
      import1.ViewContainerRef,
      import1.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    (l()(),import1.ɵted((null as any),[
      '\n    ',
      ', ',
      ' ',
      ' '
    ]
    )),
    (l()(),import1.ɵeld(0,(null as any),(null as any),0,'br',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),[
      ' \n    ',
      ''
    ]
    )),
    (l()(),import1.ɵeld(0,(null as any),(null as any),0,'br',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),[' \n']))
  ]
  ,(ck,v) => {
    var co:import3.AddressComponent = v.component;
    const currVal_1:any = co.street2;
    ck(v,5,0,currVal_1);
  },(ck,v) => {
    var co:import3.AddressComponent = v.component;
    const currVal_0:any = co.street1;
    ck(v,1,0,currVal_0);
    const currVal_2:any = co.city;
    const currVal_3:any = co.state;
    const currVal_4:any = co.postalCode;
    ck(v,6,0,currVal_2,currVal_3,currVal_4);
    const currVal_5:any = co.country;
    ck(v,8,0,currVal_5);
  });
}
function View_AddressComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'app-address',([] as any[]),(null as any),(null as any),(null as any),View_AddressComponent_0,RenderType_AddressComponent)),
    import1.ɵdid(114688,(null as any),0,import3.AddressComponent,[import4.CompanyService],(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const AddressComponentNgFactory:import1.ComponentFactory<import3.AddressComponent> = import1.ɵccf('app-address',import3.AddressComponent,View_AddressComponent_Host_0,{
  coId: 'coId',
  address: 'address'
}
,{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1ZvbHVtZXMvRy1EUklWRS9teURpcmVjdG9yeS9zZWVkX25vZGVqc0FuZ3VsYXJNeXNxbDAyL2Fzc2V0cy9hcHAvYWRkcmVzcy9hZGRyZXNzL2FkZHJlc3MuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1ZvbHVtZXMvRy1EUklWRS9teURpcmVjdG9yeS9zZWVkX25vZGVqc0FuZ3VsYXJNeXNxbDAyL2Fzc2V0cy9hcHAvYWRkcmVzcy9hZGRyZXNzL2FkZHJlc3MuY29tcG9uZW50LnRzIiwibmc6Ly8vVm9sdW1lcy9HLURSSVZFL215RGlyZWN0b3J5L3NlZWRfbm9kZWpzQW5ndWxhck15c3FsMDIvYXNzZXRzL2FwcC9hZGRyZXNzL2FkZHJlc3MvYWRkcmVzcy5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1ZvbHVtZXMvRy1EUklWRS9teURpcmVjdG9yeS9zZWVkX25vZGVqc0FuZ3VsYXJNeXNxbDAyL2Fzc2V0cy9hcHAvYWRkcmVzcy9hZGRyZXNzL2FkZHJlc3MuY29tcG9uZW50LnRzLkFkZHJlc3NDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XG4gICAge3tzdHJlZXQxfX08YnI+IFxuICAgIDxwICpuZ0lmPVwic3RyZWV0MlwiPnt7c3RyZWV0Mn19IDxicj4gPC9wPlxuICAgIHt7Y2l0eX19LCB7e3N0YXRlfX0ge3twb3N0YWxDb2RlfX0gPGJyPiBcbiAgICB7e2NvdW50cnl9fTxicj4gXG48L2Rpdj4iLCI8YXBwLWFkZHJlc3M+PC9hcHAtYWRkcmVzcz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDRUk7SUFBbUI7TUFBQTtNQUFBO0lBQUE7SUFBQTtJQUFZO0lBQUk7Ozs7SUFBaEI7SUFBQTs7Ozs7TUFGdkI7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUF1QjtNQUFBO01BQUE7SUFBQTtJQUFBO0lBQ1I7SUFBSTtJQUNmO2dCQUFBOzs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBd0M7TUFBQTtNQUFBO01BQUE7TUFBQTtJQUFBO0lBQUE7SUFDTDtJQUFJO01BQUE7TUFBQTtJQUFBO0lBQUE7SUFDNUI7SUFBSTs7OztJQUZaO0lBQUgsU0FBRyxTQUFIOzs7SUFGbUI7SUFBQTtJQUVxQjtJQUFBO0lBQUE7SUFBQTtJQUNEO0lBQUE7Ozs7O0lDSDNDO2dCQUFBOzs7SUFBQTs7Ozs7OzsifQ==
