/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './company-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './companies/companies.component.ngfactory';
import * as import4 from './company-card/company-card.component.ngfactory';
import * as import5 from './edit-company/edit-company.component.ngfactory';
import * as import6 from './company-details/company-details.component.ngfactory';
import * as import7 from './companies/companies.component';
import * as import8 from '../shared/auth-guard';
import * as import9 from './company-card/company-card.component';
import * as import10 from './edit-company/edit-company.component';
import * as import11 from './company-details/company-details.component';
class CompanyRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.CompanyRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _CompanyRoutingModule_1:import1.CompanyRoutingModule;
  _ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import3.CompaniesComponentNgFactory,
      import4.CompanyCardComponentNgFactory,
      import5.EditCompanyComponentNgFactory,
      import6.CompanyDetailsComponentNgFactory
    ]
    ,([] as any[]));
  }
  createInternal():import1.CompanyRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._CompanyRoutingModule_1 = new import1.CompanyRoutingModule();
      this._ROUTES_2 = [[
        {
          path: 'companies',
          component: import7.CompaniesComponent,
          canActivate: [import8.AuthGuard]
        }
        ,
        {
          path: 'company-card/:id',
          component: import9.CompanyCardComponent,
          canActivate: [import8.AuthGuard]
        }
        ,
        {
          path: 'edit-company',
          component: import10.EditCompanyComponent,
          canActivate: [import8.AuthGuard]
        }
        ,
        {
          path: 'edit-company/:id',
          component: import10.EditCompanyComponent,
          canActivate: [import8.AuthGuard]
        }
        ,
        {
          path: 'company-details',
          component: import11.CompanyDetailsComponent,
          canActivate: [import8.AuthGuard]
        }

      ]
    ];
    return this._CompanyRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.CompanyRoutingModule)) { return this._CompanyRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const CompanyRoutingModuleNgFactory:import0.NgModuleFactory<import1.CompanyRoutingModule> = new import0.NgModuleFactory<any>(CompanyRoutingModuleInjector,import1.CompanyRoutingModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1ZvbHVtZXMvRy1EUklWRS9teURpcmVjdG9yeS9zZWVkX25vZGVqc0FuZ3VsYXJNeXNxbDAyL2Fzc2V0cy9hcHAvY29tcGFueS9jb21wYW55LXJvdXRpbmcubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1ZvbHVtZXMvRy1EUklWRS9teURpcmVjdG9yeS9zZWVkX25vZGVqc0FuZ3VsYXJNeXNxbDAyL2Fzc2V0cy9hcHAvY29tcGFueS9jb21wYW55LXJvdXRpbmcubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
