/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './app.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/router';
import * as import4 from '@angular/platform-browser';
import * as import5 from '@angular/platform-browser/animations';
import * as import6 from '@angular/forms';
import * as import7 from '@angular/http';
import * as import8 from '@angular/material';
import * as import9 from './shared/shared.module';
import * as import10 from './company/company-routing.module';
import * as import11 from './company/company.module';
import * as import12 from '@angular/flex-layout/media-query/_module';
import * as import13 from '@angular/flex-layout/flexbox/_module';
import * as import14 from 'mydatepicker/dist/my-date-picker.module';
import * as import15 from '@angular/router/testing/src/router_testing_module';
import * as import16 from './users/users-routing.module';
import * as import17 from './users/users.module';
import * as import18 from './app-routing.module';
import * as import19 from './shared/auth-guard';
import * as import20 from './shared/password-validation';
import * as import21 from './address/address.service';
import * as import22 from './company/company.service';
import * as import23 from '@angular/flex-layout/media-query/breakpoints/break-point-registry';
import * as import24 from '@angular/flex-layout/media-query/match-media';
import * as import25 from './users/user.service';
import * as import26 from './invoice/invoice.service';
import * as import27 from './item/item.service';
import * as import28 from './shared/myglobals';
import * as import29 from '../../node_modules/@angular/material/typings/index.ngfactory';
import * as import30 from './company/companies/companies.component.ngfactory';
import * as import31 from './company/company-card/company-card.component.ngfactory';
import * as import32 from './company/edit-company/edit-company.component.ngfactory';
import * as import33 from './company/company-details/company-details.component.ngfactory';
import * as import34 from './users/login/login.component.ngfactory';
import * as import35 from './users/register/register.component.ngfactory';
import * as import36 from './users/logout/logout.component.ngfactory';
import * as import37 from './address/address-edit/address-edit.component.ngfactory';
import * as import38 from './item/item-edit/item-edit.component.ngfactory';
import * as import39 from './item/item-detail/item-detail.component.ngfactory';
import * as import40 from './invoice/invoice-edit/invoice-edit.component.ngfactory';
import * as import41 from './invoice/invoice-pre-pdf/invoice-pre-pdf.component.ngfactory';
import * as import42 from './app.component.ngfactory';
import * as import43 from '@angular/flex-layout/media-query/breakpoints/break-points-provider';
import * as import44 from '@angular/flex-layout/media-query/media-monitor-provider';
import * as import45 from '@angular/flex-layout/media-query/media-monitor';
import * as import46 from '@angular/flex-layout/media-query/observable-media-provider';
import * as import47 from '@angular/flex-layout/media-query/observable-media';
import * as import48 from './company/companies/companies.component';
import * as import49 from './company/company-card/company-card.component';
import * as import50 from './company/edit-company/edit-company.component';
import * as import51 from './company/company-details/company-details.component';
import * as import52 from './users/login/login.component';
import * as import53 from './users/register/register.component';
import * as import54 from './users/logout/logout.component';
import * as import55 from './address/address-edit/address-edit.component';
import * as import56 from './item/item-edit/item-edit.component';
import * as import57 from './item/item-detail/item-detail.component';
import * as import58 from './invoice/invoice-edit/invoice-edit.component';
import * as import59 from './invoice/invoice-pre-pdf/invoice-pre-pdf.component';
import * as import60 from '@angular/animations/browser';
import * as import61 from '@angular/flex-layout/media-query/breakpoints/break-points-token';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ErrorHandler_1:any;
  _NgProbeToken_2:any[];
  _ɵg_3:import3.ɵg;
  _APP_INITIALIZER_4:any[];
  _ApplicationInitStatus_5:import0.ApplicationInitStatus;
  _ɵf_6:import0.ɵf;
  _ApplicationRef_7:any;
  _ApplicationModule_8:import0.ApplicationModule;
  _BrowserModule_9:import4.BrowserModule;
  _BrowserAnimationsModule_10:import5.BrowserAnimationsModule;
  _ɵba_11:import6.ɵba;
  _FormsModule_12:import6.FormsModule;
  _ReactiveFormsModule_13:import6.ReactiveFormsModule;
  _HttpModule_14:import7.HttpModule;
  _MATERIAL_SANITY_CHECKS_15:any;
  _CompatibilityModule_16:import8.CompatibilityModule;
  _MdCommonModule_17:import8.MdCommonModule;
  _PlatformModule_18:import8.PlatformModule;
  _ScrollDispatchModule_19:import8.ScrollDispatchModule;
  _MdRippleModule_20:import8.MdRippleModule;
  _MdSelectionModule_21:import8.MdSelectionModule;
  _MdOptionModule_22:import8.MdOptionModule;
  _PortalModule_23:import8.PortalModule;
  _OverlayModule_24:import8.OverlayModule;
  _MdAutocompleteModule_25:import8.MdAutocompleteModule;
  _StyleModule_26:import8.StyleModule;
  _MdButtonModule_27:import8.MdButtonModule;
  _MdButtonToggleModule_28:import8.MdButtonToggleModule;
  _MdCardModule_29:import8.MdCardModule;
  _MdChipsModule_30:import8.MdChipsModule;
  _MdCheckboxModule_31:import8.MdCheckboxModule;
  _A11yModule_32:import8.A11yModule;
  _MdDialogModule_33:import8.MdDialogModule;
  _MdDatepickerModule_34:import8.MdDatepickerModule;
  _MdLineModule_35:import8.MdLineModule;
  _MdGridListModule_36:import8.MdGridListModule;
  _MdIconModule_37:import8.MdIconModule;
  _MdInputModule_38:import8.MdInputModule;
  _MdListModule_39:import8.MdListModule;
  _MdMenuModule_40:import8.MdMenuModule;
  _MdProgressBarModule_41:import8.MdProgressBarModule;
  _MdProgressSpinnerModule_42:import8.MdProgressSpinnerModule;
  _MdRadioModule_43:import8.MdRadioModule;
  _MdSelectModule_44:import8.MdSelectModule;
  _MdSidenavModule_45:import8.MdSidenavModule;
  _RtlModule_46:import8.RtlModule;
  _MdSliderModule_47:import8.MdSliderModule;
  _MdSlideToggleModule_48:import8.MdSlideToggleModule;
  _MdSnackBarModule_49:import8.MdSnackBarModule;
  _ObserveContentModule_50:import8.ObserveContentModule;
  _MdTabsModule_51:import8.MdTabsModule;
  _MdToolbarModule_52:import8.MdToolbarModule;
  _MdTooltipModule_53:import8.MdTooltipModule;
  _MaterialModule_54:import8.MaterialModule;
  _ɵa_55:any;
  _UrlSerializer_56:import3.DefaultUrlSerializer;
  _RouterOutletMap_57:import3.RouterOutletMap;
  _ROUTER_CONFIGURATION_58:any;
  _LocationStrategy_59:any;
  _Location_60:import2.Location;
  _Compiler_61:import0.Compiler;
  _NgModuleFactoryLoader_62:import0.SystemJsNgModuleLoader;
  _ROUTES_63:any[];
  _Router_64:any;
  _RouterModule_65:import3.RouterModule;
  _SharedModule_66:import9.SharedModule;
  _CompanyRoutingModule_67:import10.CompanyRoutingModule;
  _CompanyModule_68:import11.CompanyModule;
  _MediaQueriesModule_69:import12.MediaQueriesModule;
  _FlexLayoutModule_70:import13.FlexLayoutModule;
  _MyDatePickerModule_71:import14.MyDatePickerModule;
  _RouterTestingModule_72:import15.RouterTestingModule;
  _UsersRoutingModule_73:import16.UsersRoutingModule;
  _UsersModule_74:import17.UsersModule;
  _AppRoutingModule_75:import18.AppRoutingModule;
  _AppModule_76:import1.AppModule;
  __LOCALE_ID_77:any;
  __NgLocalization_78:import2.NgLocaleLocalization;
  __APP_ID_79:any;
  __IterableDiffers_80:any;
  __KeyValueDiffers_81:any;
  __DomSanitizer_82:import4.ɵe;
  __Sanitizer_83:any;
  __HAMMER_GESTURE_CONFIG_84:import8.GestureConfig;
  __EVENT_MANAGER_PLUGINS_85:any[];
  __EventManager_86:import4.EventManager;
  __ɵDomSharedStylesHost_87:import4.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_88:import4.ɵDomRendererFactory2;
  __AnimationDriver_89:any;
  __ɵAnimationStyleNormalizer_90:any;
  __ɵAnimationEngine_91:import5.ɵa;
  __RendererFactory2_92:any;
  __ɵSharedStylesHost_93:any;
  __Testability_94:import0.Testability;
  __Meta_95:import4.Meta;
  __Title_96:import4.Title;
  __ɵi_97:import6.ɵi;
  __FormBuilder_98:import6.FormBuilder;
  __BrowserXhr_99:import7.BrowserXhr;
  __ResponseOptions_100:import7.BaseResponseOptions;
  __XSRFStrategy_101:any;
  __XHRBackend_102:import7.XHRBackend;
  __RequestOptions_103:import7.BaseRequestOptions;
  __Http_104:any;
  __Platform_105:import8.Platform;
  __ScrollDispatcher_106:any;
  __ViewportRuler_107:any;
  __OverlayContainer_108:any;
  __ɵo_109:import8.ɵo;
  __Overlay_110:import8.Overlay;
  __FocusOriginMonitor_111:any;
  __UniqueSelectionDispatcher_112:any;
  __InteractivityChecker_113:import8.InteractivityChecker;
  __FocusTrapFactory_114:import8.FocusTrapFactory;
  __LiveAnnouncer_115:any;
  __MdDialog_116:import8.MdDialog;
  __MdDatepickerIntl_117:import8.MdDatepickerIntl;
  __MdIconRegistry_118:any;
  __MdSnackBar_119:import8.MdSnackBar;
  __ɵa_120:import8.ɵa;
  __AuthGuard_121:import19.AuthGuard;
  __PasswordValidation_122:import20.PasswordValidation;
  __AddressService_123:import21.AddressService;
  __CompanyService_124:import22.CompanyService;
  __BREAKPOINTS_125:any;
  __BreakPointRegistry_126:import23.BreakPointRegistry;
  __MatchMedia_127:import24.MatchMedia;
  __MediaMonitor_128:any;
  __ObservableMedia_129:any;
  __ActivatedRoute_130:any;
  __NoPreloading_131:import3.NoPreloading;
  __PreloadingStrategy_132:any;
  __RouterPreloader_133:import3.RouterPreloader;
  __PreloadAllModules_134:import3.PreloadAllModules;
  __UserService_135:import25.UserService;
  __ROUTER_INITIALIZER_136:any;
  __APP_BOOTSTRAP_LISTENER_137:any[];
  __InvoiceService_138:import26.InvoiceService;
  __ItemService_139:import27.ItemService;
  __MyGlobals_140:import28.MyGlobals;
  __RouterOutlet_141:import3.RouterOutlet;
  constructor(parent:import0.Injector) {
    super(parent,[
      import29.MdDialogContainerNgFactory,
      import29.MdDatepickerContentNgFactory,
      import29.MdSnackBarContainerNgFactory,
      import29.SimpleSnackBarNgFactory,
      import29.TooltipComponentNgFactory,
      import30.CompaniesComponentNgFactory,
      import31.CompanyCardComponentNgFactory,
      import32.EditCompanyComponentNgFactory,
      import33.CompanyDetailsComponentNgFactory,
      import34.LoginComponentNgFactory,
      import35.RegisterComponentNgFactory,
      import36.LogoutComponentNgFactory,
      import37.AddressEditComponentNgFactory,
      import38.ItemEditComponentNgFactory,
      import39.ItemDetailComponentNgFactory,
      import40.InvoiceEditComponentNgFactory,
      import41.InvoicePrePdfComponentNgFactory,
      import42.AppComponentNgFactory
    ]
    ,[import42.AppComponentNgFactory]);
  }
  get _LOCALE_ID_77():any {
    if ((this.__LOCALE_ID_77 == null)) { (this.__LOCALE_ID_77 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_77;
  }
  get _NgLocalization_78():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_78 == null)) { (this.__NgLocalization_78 = new import2.NgLocaleLocalization(this._LOCALE_ID_77)); }
    return this.__NgLocalization_78;
  }
  get _APP_ID_79():any {
    if ((this.__APP_ID_79 == null)) { (this.__APP_ID_79 = import0.ɵg()); }
    return this.__APP_ID_79;
  }
  get _IterableDiffers_80():any {
    if ((this.__IterableDiffers_80 == null)) { (this.__IterableDiffers_80 = import0.ɵl()); }
    return this.__IterableDiffers_80;
  }
  get _KeyValueDiffers_81():any {
    if ((this.__KeyValueDiffers_81 == null)) { (this.__KeyValueDiffers_81 = import0.ɵm()); }
    return this.__KeyValueDiffers_81;
  }
  get _DomSanitizer_82():import4.ɵe {
    if ((this.__DomSanitizer_82 == null)) { (this.__DomSanitizer_82 = new import4.ɵe(this.parent.get(import4.DOCUMENT))); }
    return this.__DomSanitizer_82;
  }
  get _Sanitizer_83():any {
    if ((this.__Sanitizer_83 == null)) { (this.__Sanitizer_83 = this._DomSanitizer_82); }
    return this.__Sanitizer_83;
  }
  get _HAMMER_GESTURE_CONFIG_84():import8.GestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_84 == null)) { (this.__HAMMER_GESTURE_CONFIG_84 = new import8.GestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_84;
  }
  get _EVENT_MANAGER_PLUGINS_85():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_85 == null)) { (this.__EVENT_MANAGER_PLUGINS_85 = [
      new import4.ɵDomEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵKeyEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵHammerGesturesPlugin(this.parent.get(import4.DOCUMENT),this._HAMMER_GESTURE_CONFIG_84)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_85;
  }
  get _EventManager_86():import4.EventManager {
    if ((this.__EventManager_86 == null)) { (this.__EventManager_86 = new import4.EventManager(this._EVENT_MANAGER_PLUGINS_85,this.parent.get(import0.NgZone))); }
    return this.__EventManager_86;
  }
  get _ɵDomSharedStylesHost_87():import4.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_87 == null)) { (this.__ɵDomSharedStylesHost_87 = new import4.ɵDomSharedStylesHost(this.parent.get(import4.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_87;
  }
  get _ɵDomRendererFactory2_88():import4.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_88 == null)) { (this.__ɵDomRendererFactory2_88 = new import4.ɵDomRendererFactory2(this._EventManager_86,this._ɵDomSharedStylesHost_87)); }
    return this.__ɵDomRendererFactory2_88;
  }
  get _AnimationDriver_89():any {
    if ((this.__AnimationDriver_89 == null)) { (this.__AnimationDriver_89 = import5.ɵb()); }
    return this.__AnimationDriver_89;
  }
  get _ɵAnimationStyleNormalizer_90():any {
    if ((this.__ɵAnimationStyleNormalizer_90 == null)) { (this.__ɵAnimationStyleNormalizer_90 = import5.ɵc()); }
    return this.__ɵAnimationStyleNormalizer_90;
  }
  get _ɵAnimationEngine_91():import5.ɵa {
    if ((this.__ɵAnimationEngine_91 == null)) { (this.__ɵAnimationEngine_91 = new import5.ɵa(this._AnimationDriver_89,this._ɵAnimationStyleNormalizer_90)); }
    return this.__ɵAnimationEngine_91;
  }
  get _RendererFactory2_92():any {
    if ((this.__RendererFactory2_92 == null)) { (this.__RendererFactory2_92 = import5.ɵd(this._ɵDomRendererFactory2_88,this._ɵAnimationEngine_91,this.parent.get(import0.NgZone))); }
    return this.__RendererFactory2_92;
  }
  get _ɵSharedStylesHost_93():any {
    if ((this.__ɵSharedStylesHost_93 == null)) { (this.__ɵSharedStylesHost_93 = this._ɵDomSharedStylesHost_87); }
    return this.__ɵSharedStylesHost_93;
  }
  get _Testability_94():import0.Testability {
    if ((this.__Testability_94 == null)) { (this.__Testability_94 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_94;
  }
  get _Meta_95():import4.Meta {
    if ((this.__Meta_95 == null)) { (this.__Meta_95 = new import4.Meta(this.parent.get(import4.DOCUMENT))); }
    return this.__Meta_95;
  }
  get _Title_96():import4.Title {
    if ((this.__Title_96 == null)) { (this.__Title_96 = new import4.Title(this.parent.get(import4.DOCUMENT))); }
    return this.__Title_96;
  }
  get _ɵi_97():import6.ɵi {
    if ((this.__ɵi_97 == null)) { (this.__ɵi_97 = new import6.ɵi()); }
    return this.__ɵi_97;
  }
  get _FormBuilder_98():import6.FormBuilder {
    if ((this.__FormBuilder_98 == null)) { (this.__FormBuilder_98 = new import6.FormBuilder()); }
    return this.__FormBuilder_98;
  }
  get _BrowserXhr_99():import7.BrowserXhr {
    if ((this.__BrowserXhr_99 == null)) { (this.__BrowserXhr_99 = new import7.BrowserXhr()); }
    return this.__BrowserXhr_99;
  }
  get _ResponseOptions_100():import7.BaseResponseOptions {
    if ((this.__ResponseOptions_100 == null)) { (this.__ResponseOptions_100 = new import7.BaseResponseOptions()); }
    return this.__ResponseOptions_100;
  }
  get _XSRFStrategy_101():any {
    if ((this.__XSRFStrategy_101 == null)) { (this.__XSRFStrategy_101 = import7.ɵb()); }
    return this.__XSRFStrategy_101;
  }
  get _XHRBackend_102():import7.XHRBackend {
    if ((this.__XHRBackend_102 == null)) { (this.__XHRBackend_102 = new import7.XHRBackend(this._BrowserXhr_99,this._ResponseOptions_100,this._XSRFStrategy_101)); }
    return this.__XHRBackend_102;
  }
  get _RequestOptions_103():import7.BaseRequestOptions {
    if ((this.__RequestOptions_103 == null)) { (this.__RequestOptions_103 = new import7.BaseRequestOptions()); }
    return this.__RequestOptions_103;
  }
  get _Http_104():any {
    if ((this.__Http_104 == null)) { (this.__Http_104 = import7.ɵc(this._XHRBackend_102,this._RequestOptions_103)); }
    return this.__Http_104;
  }
  get _Platform_105():import8.Platform {
    if ((this.__Platform_105 == null)) { (this.__Platform_105 = new import8.Platform()); }
    return this.__Platform_105;
  }
  get _ScrollDispatcher_106():any {
    if ((this.__ScrollDispatcher_106 == null)) { (this.__ScrollDispatcher_106 = import8.ɵf(this.parent.get(import8.ScrollDispatcher,(null as any)),this.parent.get(import0.NgZone),this._Platform_105)); }
    return this.__ScrollDispatcher_106;
  }
  get _ViewportRuler_107():any {
    if ((this.__ViewportRuler_107 == null)) { (this.__ViewportRuler_107 = import8.ɵd(this.parent.get(import8.ViewportRuler,(null as any)),this._ScrollDispatcher_106)); }
    return this.__ViewportRuler_107;
  }
  get _OverlayContainer_108():any {
    if ((this.__OverlayContainer_108 == null)) { (this.__OverlayContainer_108 = import8.ɵb(this.parent.get(import8.OverlayContainer,(null as any)))); }
    return this.__OverlayContainer_108;
  }
  get _ɵo_109():import8.ɵo {
    if ((this.__ɵo_109 == null)) { (this.__ɵo_109 = new import8.ɵo(this._ViewportRuler_107)); }
    return this.__ɵo_109;
  }
  get _Overlay_110():import8.Overlay {
    if ((this.__Overlay_110 == null)) { (this.__Overlay_110 = new import8.Overlay(this._OverlayContainer_108,this.componentFactoryResolver,this._ɵo_109,this._ApplicationRef_7,this,this.parent.get(import0.NgZone))); }
    return this.__Overlay_110;
  }
  get _FocusOriginMonitor_111():any {
    if ((this.__FocusOriginMonitor_111 == null)) { (this.__FocusOriginMonitor_111 = import8.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY(this.parent.get(import8.FocusOriginMonitor,(null as any)),this.parent.get(import0.NgZone),this._Platform_105)); }
    return this.__FocusOriginMonitor_111;
  }
  get _UniqueSelectionDispatcher_112():any {
    if ((this.__UniqueSelectionDispatcher_112 == null)) { (this.__UniqueSelectionDispatcher_112 = import8.ɵj(this.parent.get(import8.UniqueSelectionDispatcher,(null as any)))); }
    return this.__UniqueSelectionDispatcher_112;
  }
  get _InteractivityChecker_113():import8.InteractivityChecker {
    if ((this.__InteractivityChecker_113 == null)) { (this.__InteractivityChecker_113 = new import8.InteractivityChecker(this._Platform_105)); }
    return this.__InteractivityChecker_113;
  }
  get _FocusTrapFactory_114():import8.FocusTrapFactory {
    if ((this.__FocusTrapFactory_114 == null)) { (this.__FocusTrapFactory_114 = new import8.FocusTrapFactory(this._InteractivityChecker_113,this.parent.get(import0.NgZone))); }
    return this.__FocusTrapFactory_114;
  }
  get _LiveAnnouncer_115():any {
    if ((this.__LiveAnnouncer_115 == null)) { (this.__LiveAnnouncer_115 = import8.ɵi(this.parent.get(import8.LiveAnnouncer,(null as any)),this.parent.get(import8.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)),this._Platform_105)); }
    return this.__LiveAnnouncer_115;
  }
  get _MdDialog_116():import8.MdDialog {
    if ((this.__MdDialog_116 == null)) { (this.__MdDialog_116 = new import8.MdDialog(this._Overlay_110,this,this._ViewportRuler_107,this._Location_60,this.parent.get(import8.MdDialog,(null as any)))); }
    return this.__MdDialog_116;
  }
  get _MdDatepickerIntl_117():import8.MdDatepickerIntl {
    if ((this.__MdDatepickerIntl_117 == null)) { (this.__MdDatepickerIntl_117 = new import8.MdDatepickerIntl()); }
    return this.__MdDatepickerIntl_117;
  }
  get _MdIconRegistry_118():any {
    if ((this.__MdIconRegistry_118 == null)) { (this.__MdIconRegistry_118 = import8.ICON_REGISTRY_PROVIDER_FACTORY(this.parent.get(import8.MdIconRegistry,(null as any)),this._Http_104,this._DomSanitizer_82)); }
    return this.__MdIconRegistry_118;
  }
  get _MdSnackBar_119():import8.MdSnackBar {
    if ((this.__MdSnackBar_119 == null)) { (this.__MdSnackBar_119 = new import8.MdSnackBar(this._Overlay_110,this._LiveAnnouncer_115,this.parent.get(import8.MdSnackBar,(null as any)))); }
    return this.__MdSnackBar_119;
  }
  get _ɵa_120():import8.ɵa {
    if ((this.__ɵa_120 == null)) { (this.__ɵa_120 = new import8.ɵa()); }
    return this.__ɵa_120;
  }
  get _AuthGuard_121():import19.AuthGuard {
    if ((this.__AuthGuard_121 == null)) { (this.__AuthGuard_121 = new import19.AuthGuard(this._Router_64)); }
    return this.__AuthGuard_121;
  }
  get _PasswordValidation_122():import20.PasswordValidation {
    if ((this.__PasswordValidation_122 == null)) { (this.__PasswordValidation_122 = new import20.PasswordValidation()); }
    return this.__PasswordValidation_122;
  }
  get _AddressService_123():import21.AddressService {
    if ((this.__AddressService_123 == null)) { (this.__AddressService_123 = new import21.AddressService(this._Http_104)); }
    return this.__AddressService_123;
  }
  get _CompanyService_124():import22.CompanyService {
    if ((this.__CompanyService_124 == null)) { (this.__CompanyService_124 = new import22.CompanyService(this._Http_104)); }
    return this.__CompanyService_124;
  }
  get _BREAKPOINTS_125():any {
    if ((this.__BREAKPOINTS_125 == null)) { (this.__BREAKPOINTS_125 = import43.DEFAULT_BREAKPOINTS_PROVIDER_FACTORY()); }
    return this.__BREAKPOINTS_125;
  }
  get _BreakPointRegistry_126():import23.BreakPointRegistry {
    if ((this.__BreakPointRegistry_126 == null)) { (this.__BreakPointRegistry_126 = new import23.BreakPointRegistry(this._BREAKPOINTS_125)); }
    return this.__BreakPointRegistry_126;
  }
  get _MatchMedia_127():import24.MatchMedia {
    if ((this.__MatchMedia_127 == null)) { (this.__MatchMedia_127 = new import24.MatchMedia(this.parent.get(import0.NgZone))); }
    return this.__MatchMedia_127;
  }
  get _MediaMonitor_128():any {
    if ((this.__MediaMonitor_128 == null)) { (this.__MediaMonitor_128 = import44.MEDIA_MONITOR_PROVIDER_FACTORY(this.parent.get(import45.MediaMonitor,(null as any)),this._BreakPointRegistry_126,this._MatchMedia_127)); }
    return this.__MediaMonitor_128;
  }
  get _ObservableMedia_129():any {
    if ((this.__ObservableMedia_129 == null)) { (this.__ObservableMedia_129 = import46.OBSERVABLE_MEDIA_PROVIDER_FACTORY(this.parent.get(import47.ObservableMedia,(null as any)),this._MatchMedia_127,this._BreakPointRegistry_126)); }
    return this.__ObservableMedia_129;
  }
  get _ActivatedRoute_130():any {
    if ((this.__ActivatedRoute_130 == null)) { (this.__ActivatedRoute_130 = import3.ɵf(this._Router_64)); }
    return this.__ActivatedRoute_130;
  }
  get _NoPreloading_131():import3.NoPreloading {
    if ((this.__NoPreloading_131 == null)) { (this.__NoPreloading_131 = new import3.NoPreloading()); }
    return this.__NoPreloading_131;
  }
  get _PreloadingStrategy_132():any {
    if ((this.__PreloadingStrategy_132 == null)) { (this.__PreloadingStrategy_132 = this._NoPreloading_131); }
    return this.__PreloadingStrategy_132;
  }
  get _RouterPreloader_133():import3.RouterPreloader {
    if ((this.__RouterPreloader_133 == null)) { (this.__RouterPreloader_133 = new import3.RouterPreloader(this._Router_64,this._NgModuleFactoryLoader_62,this._Compiler_61,this,this._PreloadingStrategy_132)); }
    return this.__RouterPreloader_133;
  }
  get _PreloadAllModules_134():import3.PreloadAllModules {
    if ((this.__PreloadAllModules_134 == null)) { (this.__PreloadAllModules_134 = new import3.PreloadAllModules()); }
    return this.__PreloadAllModules_134;
  }
  get _UserService_135():import25.UserService {
    if ((this.__UserService_135 == null)) { (this.__UserService_135 = new import25.UserService(this._Http_104,this._Router_64)); }
    return this.__UserService_135;
  }
  get _ROUTER_INITIALIZER_136():any {
    if ((this.__ROUTER_INITIALIZER_136 == null)) { (this.__ROUTER_INITIALIZER_136 = import3.ɵi(this._ɵg_3)); }
    return this.__ROUTER_INITIALIZER_136;
  }
  get _APP_BOOTSTRAP_LISTENER_137():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_137 == null)) { (this.__APP_BOOTSTRAP_LISTENER_137 = [this._ROUTER_INITIALIZER_136]); }
    return this.__APP_BOOTSTRAP_LISTENER_137;
  }
  get _InvoiceService_138():import26.InvoiceService {
    if ((this.__InvoiceService_138 == null)) { (this.__InvoiceService_138 = new import26.InvoiceService(this._Http_104)); }
    return this.__InvoiceService_138;
  }
  get _ItemService_139():import27.ItemService {
    if ((this.__ItemService_139 == null)) { (this.__ItemService_139 = new import27.ItemService(this._Http_104,this._CompanyService_124,this._Router_64)); }
    return this.__ItemService_139;
  }
  get _MyGlobals_140():import28.MyGlobals {
    if ((this.__MyGlobals_140 == null)) { (this.__MyGlobals_140 = new import28.MyGlobals()); }
    return this.__MyGlobals_140;
  }
  get _RouterOutlet_141():import3.RouterOutlet {
    if ((this.__RouterOutlet_141 == null)) { (this.__RouterOutlet_141 = new import3.RouterOutlet(this._RouterOutletMap_57,this.parent.get(import0.ViewContainerRef),this.componentFactoryResolver,this.parent.get('name'))); }
    return this.__RouterOutlet_141;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ErrorHandler_1 = import4.ɵa();
    this._NgProbeToken_2 = [import3.ɵb()];
    this._ɵg_3 = new import3.ɵg(this);
    this._APP_INITIALIZER_4 = [
      import0.ɵo,
      import4.ɵc(this.parent.get(import4.NgProbeToken,(null as any)),this._NgProbeToken_2),
      import3.ɵh(this._ɵg_3)
    ]
    ;
    this._ApplicationInitStatus_5 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_4);
    this._ɵf_6 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_1,this.componentFactoryResolver,this._ApplicationInitStatus_5);
    this._ApplicationRef_7 = this._ɵf_6;
    this._ApplicationModule_8 = new import0.ApplicationModule(this._ApplicationRef_7);
    this._BrowserModule_9 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._BrowserAnimationsModule_10 = new import5.BrowserAnimationsModule();
    this._ɵba_11 = new import6.ɵba();
    this._FormsModule_12 = new import6.FormsModule();
    this._ReactiveFormsModule_13 = new import6.ReactiveFormsModule();
    this._HttpModule_14 = new import7.HttpModule();
    this._MATERIAL_SANITY_CHECKS_15 = true;
    this._CompatibilityModule_16 = new import8.CompatibilityModule(this.parent.get(import4.DOCUMENT,(null as any)),this._MATERIAL_SANITY_CHECKS_15);
    this._MdCommonModule_17 = new import8.MdCommonModule();
    this._PlatformModule_18 = new import8.PlatformModule();
    this._ScrollDispatchModule_19 = new import8.ScrollDispatchModule();
    this._MdRippleModule_20 = new import8.MdRippleModule();
    this._MdSelectionModule_21 = new import8.MdSelectionModule();
    this._MdOptionModule_22 = new import8.MdOptionModule();
    this._PortalModule_23 = new import8.PortalModule();
    this._OverlayModule_24 = new import8.OverlayModule();
    this._MdAutocompleteModule_25 = new import8.MdAutocompleteModule();
    this._StyleModule_26 = new import8.StyleModule();
    this._MdButtonModule_27 = new import8.MdButtonModule();
    this._MdButtonToggleModule_28 = new import8.MdButtonToggleModule();
    this._MdCardModule_29 = new import8.MdCardModule();
    this._MdChipsModule_30 = new import8.MdChipsModule();
    this._MdCheckboxModule_31 = new import8.MdCheckboxModule();
    this._A11yModule_32 = new import8.A11yModule();
    this._MdDialogModule_33 = new import8.MdDialogModule();
    this._MdDatepickerModule_34 = new import8.MdDatepickerModule();
    this._MdLineModule_35 = new import8.MdLineModule();
    this._MdGridListModule_36 = new import8.MdGridListModule();
    this._MdIconModule_37 = new import8.MdIconModule();
    this._MdInputModule_38 = new import8.MdInputModule();
    this._MdListModule_39 = new import8.MdListModule();
    this._MdMenuModule_40 = new import8.MdMenuModule();
    this._MdProgressBarModule_41 = new import8.MdProgressBarModule();
    this._MdProgressSpinnerModule_42 = new import8.MdProgressSpinnerModule();
    this._MdRadioModule_43 = new import8.MdRadioModule();
    this._MdSelectModule_44 = new import8.MdSelectModule();
    this._MdSidenavModule_45 = new import8.MdSidenavModule();
    this._RtlModule_46 = new import8.RtlModule();
    this._MdSliderModule_47 = new import8.MdSliderModule();
    this._MdSlideToggleModule_48 = new import8.MdSlideToggleModule();
    this._MdSnackBarModule_49 = new import8.MdSnackBarModule();
    this._ObserveContentModule_50 = new import8.ObserveContentModule();
    this._MdTabsModule_51 = new import8.MdTabsModule();
    this._MdToolbarModule_52 = new import8.MdToolbarModule();
    this._MdTooltipModule_53 = new import8.MdTooltipModule();
    this._MaterialModule_54 = new import8.MaterialModule();
    this._ɵa_55 = import3.ɵd(this.parent.get(import3.Router,(null as any)));
    this._UrlSerializer_56 = new import3.DefaultUrlSerializer();
    this._RouterOutletMap_57 = new import3.RouterOutletMap();
    this._ROUTER_CONFIGURATION_58 = {};
    this._LocationStrategy_59 = import3.ɵc(this.parent.get(import2.PlatformLocation),this.parent.get(import2.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_58);
    this._Location_60 = new import2.Location(this._LocationStrategy_59);
    this._Compiler_61 = new import0.Compiler();
    this._NgModuleFactoryLoader_62 = new import0.SystemJsNgModuleLoader(this._Compiler_61,this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)));
    this._ROUTES_63 = [
      [
        {
          path: 'companies',
          component: import48.CompaniesComponent,
          canActivate: [import19.AuthGuard]
        }
        ,
        {
          path: 'company-card/:id',
          component: import49.CompanyCardComponent,
          canActivate: [import19.AuthGuard]
        }
        ,
        {
          path: 'edit-company',
          component: import50.EditCompanyComponent,
          canActivate: [import19.AuthGuard]
        }
        ,
        {
          path: 'edit-company/:id',
          component: import50.EditCompanyComponent,
          canActivate: [import19.AuthGuard]
        }
        ,
        {
          path: 'company-details',
          component: import51.CompanyDetailsComponent,
          canActivate: [import19.AuthGuard]
        }

      ]
      ,
      ([] as any[]),
      [
        {
          path: 'login',
          component: import52.LoginComponent,
          name: 'Login',
          useAsDefault: true
        }
        ,
        {
          path: 'register',
          component: import53.RegisterComponent,
          name: 'Register'
        }
        ,
        {
          path: 'logout',
          component: import54.LogoutComponent,
          name: 'Logout'
        }

      ]
      ,
      [
        {
          path: '',
          redirectTo: 'register',
          pathMatch: 'full'
        }
        ,
        {
          path: 'address',
          component: import55.AddressEditComponent
        }
        ,
        {
          path: 'item-edit/:id',
          component: import56.ItemEditComponent
        }
        ,
        {
          path: 'item-edit',
          component: import56.ItemEditComponent
        }
        ,
        {
          path: 'app-item-detail',
          component: import57.ItemDetailComponent
        }
        ,
        {
          path: 'invoice-edit',
          component: import58.InvoiceEditComponent
        }
        ,
        {
          path: 'invoice-pre-pdf',
          component: import59.InvoicePrePdfComponent
        }
        ,
        {
          path: 'invoice-pre-pdf/:id',
          component: import59.InvoicePrePdfComponent
        }

      ]

    ]
    ;
    this._Router_64 = import3.ɵe(this._ApplicationRef_7,this._UrlSerializer_56,this._RouterOutletMap_57,this._Location_60,this,this._NgModuleFactoryLoader_62,this._Compiler_61,this._ROUTES_63,this._ROUTER_CONFIGURATION_58,this.parent.get(import3.UrlHandlingStrategy,(null as any)),this.parent.get(import3.RouteReuseStrategy,(null as any)));
    this._RouterModule_65 = new import3.RouterModule(this._ɵa_55,this._Router_64);
    this._SharedModule_66 = new import9.SharedModule();
    this._CompanyRoutingModule_67 = new import10.CompanyRoutingModule();
    this._CompanyModule_68 = new import11.CompanyModule();
    this._MediaQueriesModule_69 = new import12.MediaQueriesModule();
    this._FlexLayoutModule_70 = new import13.FlexLayoutModule();
    this._MyDatePickerModule_71 = new import14.MyDatePickerModule();
    this._RouterTestingModule_72 = new import15.RouterTestingModule();
    this._UsersRoutingModule_73 = new import16.UsersRoutingModule();
    this._UsersModule_74 = new import17.UsersModule();
    this._AppRoutingModule_75 = new import18.AppRoutingModule();
    this._AppModule_76 = new import1.AppModule();
    return this._AppModule_76;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_1; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_2; }
    if ((token === import3.ɵg)) { return this._ɵg_3; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_4; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_5; }
    if ((token === import0.ɵf)) { return this._ɵf_6; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_7; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_8; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_9; }
    if ((token === import5.BrowserAnimationsModule)) { return this._BrowserAnimationsModule_10; }
    if ((token === import6.ɵba)) { return this._ɵba_11; }
    if ((token === import6.FormsModule)) { return this._FormsModule_12; }
    if ((token === import6.ReactiveFormsModule)) { return this._ReactiveFormsModule_13; }
    if ((token === import7.HttpModule)) { return this._HttpModule_14; }
    if ((token === import8.MATERIAL_SANITY_CHECKS)) { return this._MATERIAL_SANITY_CHECKS_15; }
    if ((token === import8.CompatibilityModule)) { return this._CompatibilityModule_16; }
    if ((token === import8.MdCommonModule)) { return this._MdCommonModule_17; }
    if ((token === import8.PlatformModule)) { return this._PlatformModule_18; }
    if ((token === import8.ScrollDispatchModule)) { return this._ScrollDispatchModule_19; }
    if ((token === import8.MdRippleModule)) { return this._MdRippleModule_20; }
    if ((token === import8.MdSelectionModule)) { return this._MdSelectionModule_21; }
    if ((token === import8.MdOptionModule)) { return this._MdOptionModule_22; }
    if ((token === import8.PortalModule)) { return this._PortalModule_23; }
    if ((token === import8.OverlayModule)) { return this._OverlayModule_24; }
    if ((token === import8.MdAutocompleteModule)) { return this._MdAutocompleteModule_25; }
    if ((token === import8.StyleModule)) { return this._StyleModule_26; }
    if ((token === import8.MdButtonModule)) { return this._MdButtonModule_27; }
    if ((token === import8.MdButtonToggleModule)) { return this._MdButtonToggleModule_28; }
    if ((token === import8.MdCardModule)) { return this._MdCardModule_29; }
    if ((token === import8.MdChipsModule)) { return this._MdChipsModule_30; }
    if ((token === import8.MdCheckboxModule)) { return this._MdCheckboxModule_31; }
    if ((token === import8.A11yModule)) { return this._A11yModule_32; }
    if ((token === import8.MdDialogModule)) { return this._MdDialogModule_33; }
    if ((token === import8.MdDatepickerModule)) { return this._MdDatepickerModule_34; }
    if ((token === import8.MdLineModule)) { return this._MdLineModule_35; }
    if ((token === import8.MdGridListModule)) { return this._MdGridListModule_36; }
    if ((token === import8.MdIconModule)) { return this._MdIconModule_37; }
    if ((token === import8.MdInputModule)) { return this._MdInputModule_38; }
    if ((token === import8.MdListModule)) { return this._MdListModule_39; }
    if ((token === import8.MdMenuModule)) { return this._MdMenuModule_40; }
    if ((token === import8.MdProgressBarModule)) { return this._MdProgressBarModule_41; }
    if ((token === import8.MdProgressSpinnerModule)) { return this._MdProgressSpinnerModule_42; }
    if ((token === import8.MdRadioModule)) { return this._MdRadioModule_43; }
    if ((token === import8.MdSelectModule)) { return this._MdSelectModule_44; }
    if ((token === import8.MdSidenavModule)) { return this._MdSidenavModule_45; }
    if ((token === import8.RtlModule)) { return this._RtlModule_46; }
    if ((token === import8.MdSliderModule)) { return this._MdSliderModule_47; }
    if ((token === import8.MdSlideToggleModule)) { return this._MdSlideToggleModule_48; }
    if ((token === import8.MdSnackBarModule)) { return this._MdSnackBarModule_49; }
    if ((token === import8.ObserveContentModule)) { return this._ObserveContentModule_50; }
    if ((token === import8.MdTabsModule)) { return this._MdTabsModule_51; }
    if ((token === import8.MdToolbarModule)) { return this._MdToolbarModule_52; }
    if ((token === import8.MdTooltipModule)) { return this._MdTooltipModule_53; }
    if ((token === import8.MaterialModule)) { return this._MaterialModule_54; }
    if ((token === import3.ɵa)) { return this._ɵa_55; }
    if ((token === import3.UrlSerializer)) { return this._UrlSerializer_56; }
    if ((token === import3.RouterOutletMap)) { return this._RouterOutletMap_57; }
    if ((token === import3.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_58; }
    if ((token === import2.LocationStrategy)) { return this._LocationStrategy_59; }
    if ((token === import2.Location)) { return this._Location_60; }
    if ((token === import0.Compiler)) { return this._Compiler_61; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_62; }
    if ((token === import3.ROUTES)) { return this._ROUTES_63; }
    if ((token === import3.Router)) { return this._Router_64; }
    if ((token === import3.RouterModule)) { return this._RouterModule_65; }
    if ((token === import9.SharedModule)) { return this._SharedModule_66; }
    if ((token === import10.CompanyRoutingModule)) { return this._CompanyRoutingModule_67; }
    if ((token === import11.CompanyModule)) { return this._CompanyModule_68; }
    if ((token === import12.MediaQueriesModule)) { return this._MediaQueriesModule_69; }
    if ((token === import13.FlexLayoutModule)) { return this._FlexLayoutModule_70; }
    if ((token === import14.MyDatePickerModule)) { return this._MyDatePickerModule_71; }
    if ((token === import15.RouterTestingModule)) { return this._RouterTestingModule_72; }
    if ((token === import16.UsersRoutingModule)) { return this._UsersRoutingModule_73; }
    if ((token === import17.UsersModule)) { return this._UsersModule_74; }
    if ((token === import18.AppRoutingModule)) { return this._AppRoutingModule_75; }
    if ((token === import1.AppModule)) { return this._AppModule_76; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_77; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_78; }
    if ((token === import0.APP_ID)) { return this._APP_ID_79; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_80; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_81; }
    if ((token === import4.DomSanitizer)) { return this._DomSanitizer_82; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_83; }
    if ((token === import4.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_84; }
    if ((token === import4.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_85; }
    if ((token === import4.EventManager)) { return this._EventManager_86; }
    if ((token === import4.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_87; }
    if ((token === import4.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_88; }
    if ((token === import60.AnimationDriver)) { return this._AnimationDriver_89; }
    if ((token === import60.ɵAnimationStyleNormalizer)) { return this._ɵAnimationStyleNormalizer_90; }
    if ((token === import60.ɵAnimationEngine)) { return this._ɵAnimationEngine_91; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_92; }
    if ((token === import4.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_93; }
    if ((token === import0.Testability)) { return this._Testability_94; }
    if ((token === import4.Meta)) { return this._Meta_95; }
    if ((token === import4.Title)) { return this._Title_96; }
    if ((token === import6.ɵi)) { return this._ɵi_97; }
    if ((token === import6.FormBuilder)) { return this._FormBuilder_98; }
    if ((token === import7.BrowserXhr)) { return this._BrowserXhr_99; }
    if ((token === import7.ResponseOptions)) { return this._ResponseOptions_100; }
    if ((token === import7.XSRFStrategy)) { return this._XSRFStrategy_101; }
    if ((token === import7.XHRBackend)) { return this._XHRBackend_102; }
    if ((token === import7.RequestOptions)) { return this._RequestOptions_103; }
    if ((token === import7.Http)) { return this._Http_104; }
    if ((token === import8.Platform)) { return this._Platform_105; }
    if ((token === import8.ScrollDispatcher)) { return this._ScrollDispatcher_106; }
    if ((token === import8.ViewportRuler)) { return this._ViewportRuler_107; }
    if ((token === import8.OverlayContainer)) { return this._OverlayContainer_108; }
    if ((token === import8.ɵo)) { return this._ɵo_109; }
    if ((token === import8.Overlay)) { return this._Overlay_110; }
    if ((token === import8.FocusOriginMonitor)) { return this._FocusOriginMonitor_111; }
    if ((token === import8.UniqueSelectionDispatcher)) { return this._UniqueSelectionDispatcher_112; }
    if ((token === import8.InteractivityChecker)) { return this._InteractivityChecker_113; }
    if ((token === import8.FocusTrapFactory)) { return this._FocusTrapFactory_114; }
    if ((token === import8.LiveAnnouncer)) { return this._LiveAnnouncer_115; }
    if ((token === import8.MdDialog)) { return this._MdDialog_116; }
    if ((token === import8.MdDatepickerIntl)) { return this._MdDatepickerIntl_117; }
    if ((token === import8.MdIconRegistry)) { return this._MdIconRegistry_118; }
    if ((token === import8.MdSnackBar)) { return this._MdSnackBar_119; }
    if ((token === import8.ɵa)) { return this._ɵa_120; }
    if ((token === import19.AuthGuard)) { return this._AuthGuard_121; }
    if ((token === import20.PasswordValidation)) { return this._PasswordValidation_122; }
    if ((token === import21.AddressService)) { return this._AddressService_123; }
    if ((token === import22.CompanyService)) { return this._CompanyService_124; }
    if ((token === import61.BREAKPOINTS)) { return this._BREAKPOINTS_125; }
    if ((token === import23.BreakPointRegistry)) { return this._BreakPointRegistry_126; }
    if ((token === import24.MatchMedia)) { return this._MatchMedia_127; }
    if ((token === import45.MediaMonitor)) { return this._MediaMonitor_128; }
    if ((token === import47.ObservableMedia)) { return this._ObservableMedia_129; }
    if ((token === import3.ActivatedRoute)) { return this._ActivatedRoute_130; }
    if ((token === import3.NoPreloading)) { return this._NoPreloading_131; }
    if ((token === import3.PreloadingStrategy)) { return this._PreloadingStrategy_132; }
    if ((token === import3.RouterPreloader)) { return this._RouterPreloader_133; }
    if ((token === import3.PreloadAllModules)) { return this._PreloadAllModules_134; }
    if ((token === import25.UserService)) { return this._UserService_135; }
    if ((token === import3.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_136; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_137; }
    if ((token === import26.InvoiceService)) { return this._InvoiceService_138; }
    if ((token === import27.ItemService)) { return this._ItemService_139; }
    if ((token === import28.MyGlobals)) { return this._MyGlobals_140; }
    if ((token === import3.RouterOutlet)) { return this._RouterOutlet_141; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_6.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_87 && this._ɵDomSharedStylesHost_87.ngOnDestroy());
    (this.__RouterPreloader_133 && this._RouterPreloader_133.ngOnDestroy());
    (this.__RouterOutlet_141 && this._RouterOutlet_141.ngOnDestroy());
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1ZvbHVtZXMvRy1EUklWRS9teURpcmVjdG9yeS9zZWVkX25vZGVqc0FuZ3VsYXJNeXNxbDAyL2Fzc2V0cy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Wb2x1bWVzL0ctRFJJVkUvbXlEaXJlY3Rvcnkvc2VlZF9ub2RlanNBbmd1bGFyTXlzcWwwMi9hc3NldHMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
